site_name: Passport.js

# change document

nav:
  - Home: 'index.md'
  - Steps:
    - Preliminary: 'preliminary.md'
    - Routes: 'routes.md'
    - Strategies: 'strategies.md'
  - Glossary: 'glossary.md'