site_name: 'Passport'

# change document

nav:
  - Home: 'index.md'
  - Instructions:
    - Preliminary Setup: 'preliminary.md'
    - Routes: 'routes.md'
    - Strategies: 'strategies.md'
  - Troubleshooting: 'trouble.md'
  - Glossary: 'glossary.md'