site_name: 'Passport'

# change document

theme:
  name: 'material'

markdown_extensions:
  - 'admonition'
  - 'pymdownx.details'
  - 'pymdownx.superfences'

htmltitle: 'Passport.js Local Strategy'

nav:
  - Home: 'index.md'
  - Instructions:
    - Preliminary Setup: 'preliminary.md'
    - Strategies: 'strategies.md'
    - Routes: 'routes.md'
  - Troubleshooting: 'trouble.md'
  - Glossary: 'glossary.md'